In [2]:
import pandas as pd
import pickle
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
CovidTravelDF = pd.read_csv("US_Covid_and_Travel_Data.csv")

CovidTravelDF.head()

,Year,Month_number,Month,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths,Foreign_originating,Foreign_returning,US_citizen_originating,US_citizen_returning,Timestamp
0,2020,1,January,8,8,0,0,5274405,5520357,4073096,5218812,2020-01
1,2020,2,February,61,69,1,1,4470729,4448720,3902937,4155775,2020-02
2,2020,3,March,173074,173143,3326,3327,1960896,2946059,1844726,3053096,2020-03
3,2020,4,April,857163,1030306,57134,60461,54031,176627,32144,110285,2020-04
4,2020,5,May,755116,1785422,44864,105325,78337,192614,54368,107630,2020-05

In [ ]:
CovidTravelDF = titanicDf[["PassengerId", "Age"]]